PROGRAM BRAVO
	IMPLICIT NONE
	INTEGER :: A, B, C, D, E, F
	INTEGER :: IOS

	PRINT *, "PROGRAM BRAVO"
	PRINT *, "TESTING READING NUMBERS AND IGNORING CHARACTERS"
	PRINT *, "PRESS ENTER TO CONTINUE"
	READ(*, *)

	OPEN( unit=10, file="bravo_in.txt" )

	READ( 10, *, iostat=IOS ) A, B, C
	PRINT *, "1ST UNFORMATTED READ"
	PRINT *, "SHOULD READ THE FIRST 3 NUMBERS FINE"
	PRINT *, "NUMBERS ARE:", A, B, C

	IF ( IOS .eq. 0 ) THEN
		READ( 10, *, iostat=IOS ) A, B
		PRINT *, "2ND UNFORMATTED READ"
		PRINT *, "WILL IT READ 2 NUM FROM 2ND LINE OR 2 CHAR ON 1ST LINE?"
		PRINT *, "VARIABLES ARE:", A, B
	ENDIF

	IF ( IOS .eq. 0 ) THEN
		READ ( 10, *, iostat=IOS ) A
		PRINT *, "3RD UNFORMATTED READ"
		PRINT *, "VARS ARE:", A
	ENDIF

	IF ( IOS .eq. 0 ) THEN
		READ ( 10, *, iostat=IOS ) A, B, C, D
		PRINT *, "4TH UNFORMATTED READ"
		PRINT *, "VARS ARE:", A, B, C, D
	ENDIF

	CLOSE( 10 )

END PROGRAM
