PROGRAM CHARLIE
	IMPLICIT NONE
	INTEGER, PARAMETER :: MAX_NUM = 32
	INTEGER, DIMENSION(MAX_NUM) :: OUTPUT_NUM
	INTEGER :: I

	PRINT *, "PROGRAM CHARLIE: TESTING FORMATTED OUTPUT STATEMENTS"
	PRINT *, "PRESS ENTER TO CONTINUE"
	READ (*, *)

	OPEN ( unit=11, file="charlie_out.txt" )

	!write header out to file
	WRITE (11, *) "CHARLIE_OUT.TXT"
	WRITE (11, *) "THE SPACE AT THE BEGINNING IS FOR THE PRINTER (I THINK?)"

	!initialize
	DO I=1, MAX_NUM
		OUTPUT_NUM(I) = I
	ENDDO

	!mi corazon late como un burro sin ?micate? (rope?)
	!practicing my formatted outputs
	WRITE (11, "(5I3)") OUTPUT_NUM(1), OUTPUT_NUM(2), OUTPUT_NUM(3), OUTPUT_NUM(4), OUTPUT_NUM(5)
	WRITE (11, "(3I3)") OUTPUT_NUM(6), OUTPUT_NUM(7), OUTPUT_NUM(8)

	WRITE (11, "(7I8)") OUTPUT_NUM(9), OUTPUT_NUM(10), OUTPUT_NUM(11), OUTPUT_NUM(12), OUTPUT_NUM(13), OUTPUT_NUM(14), OUTPUT_NUM(15)
	WRITE (11, "(7I3)") OUTPUT_NUM(16), OUTPUT_NUM(17), OUTPUT_NUM(18), OUTPUT_NUM(19), OUTPUT_NUM(20), OUTPUT_NUM(21), OUTPUT_NUM(22)


	!trying to figure out how to get rid of the space at the beginning
	!of each line
	100 FORMAT(" ", "DON'T WANT THE PRINTER CONTROL HERE")
	WRITE( 11, 100 )

	101 FORMAT(" ", 4I3)
	WRITE( 11, 101 ) OUTPUT_NUM(23), OUTPUT_NUM(24), OUTPUT_NUM(25), OUTPUT_NUM(26)

	102 FORMAT( "MAYBE TRY IT WITH NO SPACE AT BEGINNING?" )
	WRITE( 11, 102 )

	103 FORMAT( 4I3 )
	WRITE( 11, 103 ) OUTPUT_NUM(27), OUTPUT_NUM(28), OUTPUT_NUM(29), OUTPUT_NUM(30)

	WRITE(11, *) !BLANK LINE
	WRITE(11, *) "HERE ARE SOME UNFORMATTED WRITES"
	WRITE(11, *) OUTPUT_NUM(31), OUTPUT_NUM(32)

	PRINT *, "END"

	CLOSE (11)
END PROGRAM
